/* ================================================================
   shared.js — GitHub Skills Tracker · shared app logic
   Each page sets window.PAGE_CONFIG before loading this file.
================================================================ */

/* ── i18n ──────────────────────────────────────────────────────── */
const I18N = {
  zh: {
    nav_skills:    'Skills 排行榜',
    nav_research:  'Auto Research',
    nav_favorites: '收藏',
    skills_title:  'GitHub Skills 排行榜',
    skills_sub:    '追踪 GitHub 上热门 AI Skills 仓库',
    research_title:'Auto Research 排行榜',
    research_sub:  '追踪 GitHub 上热门 AI 自动研究工具',
    search_skills: '搜索 Skills…',
    search_research:'搜索 Research 工具…',
    lang_label:    '语言',
    lang_all:      '所有语言',
    stars_all:     '全部',
    time_all:      '全部时间',
    time_1m:       '近 1 月',
    time_3m:       '近 3 月',
    time_1y:       '近 1 年',
    view_grid:     '⊞ 网格',
    view_list:     '≡ 列表',
    tab_all:       '全部',
    af_label:      '筛选：',
    af_clear:      '清除全部',
    no_results:    '没有符合条件的仓库',
    no_results_sub:'请尝试其他关键词或清除筛选条件',
    no_fav:        '还没有收藏的仓库',
    no_fav_sub:    '点击卡片右上角的 ♡ 收藏感兴趣的仓库',
    no_desc:       '暂无描述',
    footer:        '数据由 fetch_data.py 生成 · 来源 GitHub Search API · 每周自动更新',
    col_rank:      '排名',
    col_repo:      '仓库',
    col_stars:     'Stars',
    col_uses:      '用途',
    col_cat:       '分类',
    col_lang:      '语言',
    col_updated:   '更新',
    stat_repos:    '个仓库',
    stat_min:      '星起收录',
    stat_updated:  '更新于',
    stat_top:      '最高',
  },
  en: {
    nav_skills:    'Skills',
    nav_research:  'Auto Research',
    nav_favorites: 'Favorites',
    skills_title:  'GitHub Skills Leaderboard',
    skills_sub:    'Tracking top AI Skills repositories on GitHub',
    research_title:'Auto Research Leaderboard',
    research_sub:  'Tracking top AI Research tools on GitHub',
    search_skills: 'Search Skills…',
    search_research:'Search Research tools…',
    lang_label:    'Language',
    lang_all:      'All Languages',
    stars_all:     'All',
    time_all:      'All time',
    time_1m:       'Past month',
    time_3m:       'Past 3 months',
    time_1y:       'Past year',
    view_grid:     '⊞ Grid',
    view_list:     '≡ List',
    tab_all:       'All',
    af_label:      'Filters: ',
    af_clear:      'Clear all',
    no_results:    'No matching repositories',
    no_results_sub:'Try other keywords or clear filters',
    no_fav:        'No saved repositories',
    no_fav_sub:    'Click ♡ on any card to save it',
    no_desc:       'No description',
    footer:        'Generated by fetch_data.py · Source: GitHub Search API · Updated weekly',
    col_rank:      'Rank',
    col_repo:      'Repository',
    col_stars:     'Stars',
    col_uses:      'Use Cases',
    col_cat:       'Category',
    col_lang:      'Language',
    col_updated:   'Updated',
    stat_repos:    'repositories',
    stat_min:      '+ stars min',
    stat_updated:  'Updated',
    stat_top:      'Top',
  }
};

/* ── Use-case label translations ────────────────────────────────── */
const UC_EN = {
  "AI 代理":"AI Agents","工具集成":"Tools","工作流自动化":"Automation",
  "Prompt 优化":"Prompts","UI/UX 设计":"UI/UX","资源列表":"Awesome List",
  "知识管理":"Knowledge","搜索":"Search","数据分析":"Data","写作/内容":"Writing",
  "代码生成":"Code Gen","代码审查":"Review","文档生成":"Docs","测试":"Testing",
  "DevOps":"DevOps","安全":"Security","任务规划":"Planning","Web 开发":"Web Dev",
  "模型路由":"Routing","游戏开发":"Game Dev","通用工具":"General",
  "自主代理":"Autonomous","代码研究":"Code Research","知识库":"KBase",
  "学术文献":"Literature","深度研究":"Deep Res.","金融数据":"Finance",
  "实验自动化":"Lab Auto","网页搜索":"Web Search","AI 训练":"AI Train",
  "睡眠/后台":"Background","竞争分析":"Competitive","通用研究":"General",
};

/* ── Category label translations (for research cats) ────────────── */
const CAT_EN = {
  "深度研究":"Deep Research","网页研究":"Web Research","文献综述":"Literature",
  "数据分析":"Data Analysis","知识管理":"Knowledge Base","通用研究":"General",
  "其他 AI":"Other AI",
};

/* ── App State ──────────────────────────────────────────────────── */
const app = {
  data:         null,
  allRepos:     [],
  filtered:     [],
  lang:         localStorage.getItem('st_lang')  || 'zh',
  theme:        localStorage.getItem('st_theme') || 'dark',
  activeTab:    'all',
  searchQ:      '',
  language:     '',
  minStars:     0,
  maxDaysOld:   0,
  selectedUCs:  new Set(),
  viewMode:     localStorage.getItem('st_view') || 'grid',
  favOnly:      false,
  favorites:    new Set(JSON.parse(localStorage.getItem('st_favorites') || '[]')),
  currentPage:  1,
  pageSize:     24,
  pageConfig:   null,
};

/* ── Translation helper ─────────────────────────────────────────── */
function t(key) {
  return (I18N[app.lang] || I18N.zh)[key] || key;
}
function tUC(label) {
  if (app.lang === 'en') return UC_EN[label] || label;
  return label;
}
function tCat(label) {
  if (app.lang === 'en') return CAT_EN[label] || label;
  return label;
}

/* ── Number helpers ─────────────────────────────────────────────── */
function fmtNum(n) {
  if (n >= 1000) return (n / 1000).toFixed(1).replace(/\.0$/, '') + 'k';
  return String(n);
}
function timeAgo(iso) {
  const d = Math.floor((Date.now() - new Date(iso)) / 86400000);
  if (d === 0) return t('today') || (app.lang === 'en' ? 'Today' : '今天');
  if (d === 1) return app.lang === 'en' ? 'Yesterday' : '昨天';
  if (d < 30)  return app.lang === 'en' ? `${d}d ago` : `${d}天前`;
  if (d < 365) return app.lang === 'en' ? `${Math.floor(d/30)}mo ago` : `${Math.floor(d/30)}月前`;
  return app.lang === 'en' ? `${Math.floor(d/365)}yr ago` : `${Math.floor(d/365)}年前`;
}

/* ── Init ───────────────────────────────────────────────────────── */
function init(config) {
  app.pageConfig = config;

  // apply stored theme
  document.documentElement.dataset.theme = app.theme === 'light' ? 'light' : 'dark';

  // load data
  const raw = window[config.dataKey];
  if (!raw) {
    document.getElementById('noData').style.display = 'block';
    document.getElementById('grid').innerHTML =
      `<div class="empty-state"><span class="icon">📭</span>${config.noDataHint}</div>`;
    renderNav();
    return;
  }
  app.data     = raw;
  app.allRepos = raw.repos;

  renderNav();
  renderHero();
  renderTabs();
  renderUCChips();
  renderLangSelect();
  applyFilters();
  applyThemeBtn();
  applyLangBtn();
}

/* ── Theme ──────────────────────────────────────────────────────── */
function toggleTheme() {
  app.theme = app.theme === 'dark' ? 'light' : 'dark';
  localStorage.setItem('st_theme', app.theme);
  document.documentElement.dataset.theme = app.theme;
  applyThemeBtn();
}
function applyThemeBtn() {
  const btn = document.getElementById('themeBtn');
  if (btn) btn.textContent = app.theme === 'dark' ? '☀️' : '🌙';
}

/* ── Language ───────────────────────────────────────────────────── */
function toggleLang() {
  app.lang = app.lang === 'zh' ? 'en' : 'zh';
  localStorage.setItem('st_lang', app.lang);
  renderAll();
}
function applyLangBtn() {
  const btn = document.getElementById('langBtn');
  if (btn) btn.textContent = app.lang === 'zh' ? 'EN' : '中';
}

/* ── Favorites ──────────────────────────────────────────────────── */
function toggleFav(id, btn) {
  if (app.favorites.has(id)) {
    app.favorites.delete(id);
    btn.classList.remove('saved');
    btn.title = '';
  } else {
    app.favorites.add(id);
    btn.classList.add('saved');
  }
  localStorage.setItem('st_favorites', JSON.stringify([...app.favorites]));
  updateFavBtn();
  if (app.favOnly) applyFilters();
}
function toggleFavOnly() {
  app.favOnly = !app.favOnly;
  app.currentPage = 1;
  const btn = document.getElementById('favBtn');
  if (btn) btn.classList.toggle('active', app.favOnly);
  applyFilters();
}
function updateFavBtn() {
  const cnt = document.querySelector('.fav-count');
  if (!cnt) return;
  cnt.textContent = app.favorites.size;
  cnt.classList.toggle('visible', app.favorites.size > 0);
}

/* ── Nav render ─────────────────────────────────────────────────── */
function renderNav() {
  const isSkills   = app.pageConfig.page === 'skills';
  const isResearch = app.pageConfig.page === 'research';
  const nav = document.getElementById('navbar');
  if (!nav) return;
  nav.innerHTML = `
    <a class="nav-brand" href="index.html">
      <img src="favicon.svg" alt="logo" />
      <span class="nav-brand-text">Skills Tracker</span>
    </a>
    <div class="nav-links">
      <a class="nav-link${isSkills ? ' active' : ''}" href="index.html">
        ⚡ <span class="full">${t('nav_skills')}</span>
      </a>
      <a class="nav-link${isResearch ? ' active' : ''}" href="auto-research.html">
        🔬 <span class="full">${t('nav_research')}</span>
      </a>
    </div>
    <div class="nav-actions">
      <button class="nav-btn${app.favOnly ? ' active' : ''}" id="favBtn" onclick="toggleFavOnly()">
        ❤ ${t('nav_favorites')} <span class="fav-count${app.favorites.size > 0 ? ' visible' : ''}">${app.favorites.size}</span>
      </button>
      <button class="nav-btn" id="langBtn" onclick="toggleLang()">
        ${app.lang === 'zh' ? 'EN' : '中'}
      </button>
      <button class="nav-btn" id="themeBtn" onclick="toggleTheme()">
        ${app.theme === 'dark' ? '☀️' : '🌙'}
      </button>
    </div>`;
}

/* ── Hero render ────────────────────────────────────────────────── */
function renderHero() {
  const m = app.data.meta;
  const d = new Date(m.updated_at);
  const updated = d.toLocaleString(app.lang === 'zh' ? 'zh-CN' : 'en-US',
    { month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' });
  const top = app.allRepos[0]?.stars ?? 0;
  const cfg = app.pageConfig;

  const titleKey = cfg.page === 'skills' ? 'skills_title' : 'research_title';
  const subKey   = cfg.page === 'skills' ? 'skills_sub'   : 'research_sub';

  const heroEl = document.getElementById('hero');
  if (!heroEl) return;
  heroEl.innerHTML = `
    <div class="hero-logo">
      <img src="favicon.svg" alt="logo" />
      <h1>${t(titleKey)}</h1>
    </div>
    <p class="hero-sub">${t(subKey)}</p>
    <div class="hero-meta">
      <span class="meta-pill"><strong>${m.total}</strong> ${t('stat_repos')}</span>
      <span class="meta-pill"><strong>★${m.min_stars}+</strong> ${t('stat_min')}</span>
      <span class="meta-pill">${t('stat_updated')} <strong>${updated}</strong></span>
      <span class="meta-pill">${t('stat_top')} <strong>★${fmtNum(top)}</strong></span>
    </div>`;
}

/* ── Tabs ───────────────────────────────────────────────────────── */
function renderTabs() {
  const tabs = document.getElementById('tabs');
  if (!tabs) return;
  const cats = app.data.categories;
  const all  = app.allRepos.length;

  const items = [{ id:'all', label: t('tab_all'), icon:'🌐', count: all }];
  Object.entries(cats).forEach(([id, meta]) => {
    items.push({ id, label: tCat(meta.label), icon: meta.icon, count: meta.count });
  });

  tabs.innerHTML = items.map(it => `
    <button class="tab${it.id === app.activeTab ? ' active' : ''}" data-id="${it.id}"
            onclick="setTab('${it.id}')">
      ${it.icon} ${it.label} <span class="cnt">${it.count}</span>
    </button>`).join('');
}

function setTab(id) {
  app.activeTab  = id;
  app.currentPage = 1;
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.id === id));
  applyFilters();
}

/* ── Language select ─────────────────────────────────────────────── */
function renderLangSelect() {
  const sel = document.getElementById('langSelect');
  if (!sel || !app.data) return;
  const langs = [...new Set(app.allRepos.map(r => r.language).filter(Boolean))].sort();
  sel.innerHTML = `<option value="">${t('lang_all')}</option>` +
    langs.map(l => `<option value="${l}"${app.language === l ? ' selected' : ''}>${l}</option>`).join('');
}

/* ── Use-case chips ─────────────────────────────────────────────── */
function renderUCChips() {
  const row = document.getElementById('ucScroller');
  if (!row || !app.data) return;
  const stats = app.data.use_case_stats || {};
  row.innerHTML = Object.entries(stats)
    .sort((a, b) => b[1] - a[1])
    .map(([uc, cnt]) => `
      <span class="uc-chip${app.selectedUCs.has(uc) ? ' active' : ''}"
            onclick="toggleUC('${uc}')" data-uc="${uc}">
        ${tUC(uc)} <span class="uc-cnt">${cnt}</span>
      </span>`).join('');
}

function toggleUC(uc) {
  if (app.selectedUCs.has(uc)) app.selectedUCs.delete(uc);
  else app.selectedUCs.add(uc);
  document.querySelectorAll('.uc-chip').forEach(el =>
    el.classList.toggle('active', app.selectedUCs.has(el.dataset.uc)));
  app.currentPage = 1;
  applyFilters();
}

/* ── Filter bar controls ─────────────────────────────────────────── */
function onSearch() {
  app.searchQ     = document.getElementById('searchInput').value.toLowerCase();
  app.currentPage = 1;
  applyFilters();
}
function onLangChange() {
  app.language    = document.getElementById('langSelect').value;
  app.currentPage = 1;
  applyFilters();
}
function setStars(val) {
  app.minStars    = parseInt(val);
  app.currentPage = 1;
  document.querySelectorAll('.stars-preset .preset-btn').forEach(b =>
    b.classList.toggle('active', parseInt(b.dataset.val) === app.minStars));
  applyFilters();
}
function setTime(val) {
  app.maxDaysOld  = parseInt(val);
  app.currentPage = 1;
  document.querySelectorAll('.time-preset .preset-btn').forEach(b =>
    b.classList.toggle('active', parseInt(b.dataset.val) === app.maxDaysOld));
  applyFilters();
}
function setPageSize(val) {
  app.pageSize    = parseInt(val);
  app.currentPage = 1;
  applyFilters();
}
function setView(mode) {
  app.viewMode = mode;
  localStorage.setItem('st_view', mode);
  document.querySelectorAll('.view-btn').forEach(b =>
    b.classList.toggle('active', b.dataset.mode === mode));
  renderContent();
}

/* ── Clear all filters ──────────────────────────────────────────── */
function clearFilters() {
  app.searchQ    = '';
  app.language   = '';
  app.minStars   = 0;
  app.maxDaysOld = 0;
  app.selectedUCs.clear();
  app.favOnly    = false;
  app.activeTab  = 'all';
  app.currentPage = 1;

  const si = document.getElementById('searchInput');   if (si) si.value = '';
  const ls = document.getElementById('langSelect');    if (ls) ls.value = '';
  document.querySelectorAll('.preset-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.preset-btn[data-val="0"]').forEach(b => b.classList.add('active'));
  document.querySelectorAll('.uc-chip').forEach(c => c.classList.remove('active'));
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.id === 'all'));
  const fb = document.getElementById('favBtn'); if (fb) fb.classList.remove('active');
  applyFilters();
}

/* ── Apply filters ──────────────────────────────────────────────── */
function applyFilters() {
  let list = app.activeTab === 'all'
    ? app.allRepos
    : app.allRepos.filter(r => r.category === app.activeTab);

  if (app.favOnly)    list = list.filter(r => app.favorites.has(r.id));
  if (app.searchQ)    list = list.filter(r => (r.full_name + ' ' + r.description).toLowerCase().includes(app.searchQ));
  if (app.language)   list = list.filter(r => r.language === app.language);
  if (app.minStars)   list = list.filter(r => r.stars >= app.minStars);
  if (app.maxDaysOld) {
    const cutoff = Date.now() - app.maxDaysOld * 86400000;
    list = list.filter(r => new Date(r.updated_at) >= cutoff);
  }
  if (app.selectedUCs.size) {
    list = list.filter(r => r.use_cases.some(uc => app.selectedUCs.has(uc)));
  }

  // sort: stars (default since data is pre-sorted)
  app.filtered = list;
  renderActiveFilters();
  renderContent();
  renderPagination();
}

/* ── Active filters bar ─────────────────────────────────────────── */
function renderActiveFilters() {
  const bar = document.getElementById('activeFilters');
  if (!bar) return;
  const chips = [];

  if (app.searchQ)    chips.push({ label: `"${app.searchQ}"`,   clear: () => { app.searchQ = ''; document.getElementById('searchInput').value = ''; } });
  if (app.language)   chips.push({ label: app.language,          clear: () => { app.language = ''; document.getElementById('langSelect').value = ''; } });
  if (app.minStars)   chips.push({ label: `★${fmtNum(app.minStars)}+`, clear: () => setStars(0) });
  if (app.maxDaysOld) chips.push({ label: app.maxDaysOld <= 30 ? t('time_1m') : app.maxDaysOld <= 90 ? t('time_3m') : t('time_1y'), clear: () => setTime(0) });
  app.selectedUCs.forEach(uc => chips.push({ label: tUC(uc), clear: () => toggleUC(uc) }));
  if (app.favOnly)    chips.push({ label: '❤ ' + t('nav_favorites'), clear: () => { app.favOnly = false; document.getElementById('favBtn')?.classList.remove('active'); } });

  if (!chips.length) { bar.classList.add('hidden'); return; }
  bar.classList.remove('hidden');
  bar.innerHTML = `
    <span class="af-label">${t('af_label')}</span>
    ${chips.map((c, i) => `<span class="af-chip" onclick="removeFilter(${i})">${c.label}</span>`).join('')}
    <button class="af-clear" onclick="clearFilters()">${t('af_clear')}</button>`;
  bar._chips = chips;
}
function removeFilter(i) {
  const bar = document.getElementById('activeFilters');
  if (!bar || !bar._chips) return;
  bar._chips[i].clear();
  app.currentPage = 1;
  applyFilters();
}

/* ── Render content (grid or list) ─────────────────────────────── */
function renderContent() {
  if (app.viewMode === 'list') renderList();
  else renderGrid();
}

/* ── Grid ───────────────────────────────────────────────────────── */
const STAR_SVG = `<svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor" style="vertical-align:-1px"><path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.75.75 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25z"/></svg>`;

function renderGrid() {
  const grid = document.getElementById('grid');
  if (!grid) return;
  grid.style.display = '';
  const table = document.getElementById('listTable');
  if (table) table.style.display = 'none';

  const start = (app.currentPage - 1) * app.pageSize;
  const page  = app.filtered.slice(start, start + app.pageSize);
  const rankMap = new Map(app.allRepos.map((r, i) => [r.id, i + 1]));

  if (!page.length) {
    const msg = app.favOnly
      ? `<div class="empty-state"><span class="icon">🤍</span><strong>${t('no_fav')}</strong><p>${t('no_fav_sub')}</p></div>`
      : `<div class="empty-state"><span class="icon">🔍</span><strong>${t('no_results')}</strong><p>${t('no_results_sub')}</p></div>`;
    grid.innerHTML = msg;
    return;
  }

  grid.innerHTML = page.map(repo => cardHTML(repo, rankMap.get(repo.id) ?? 999)).join('');
}

function cardHTML(repo, gr) {
  const rankCls  = gr <= 3 ? ` rank-${gr}` : '';
  const emoji    = gr === 1 ? '🥇' : gr === 2 ? '🥈' : gr === 3 ? '🥉' : null;
  const rankLbl  = emoji ? `${emoji} #${gr}` : `#${gr}`;
  const [owner, name] = repo.full_name.split('/');
  const isSaved  = app.favorites.has(repo.id);
  const cats = app.data.categories;
  const catLbl = tCat(cats[repo.category]?.label || repo.category);
  const catIcon = cats[repo.category]?.icon || '';
  const ucTags = (repo.use_cases || []).slice(0, 4).map(uc =>
    `<span class="uc-tag${app.selectedUCs.has(uc) ? ' active' : ''}"
           onclick="event.preventDefault();toggleUC('${uc}')">${tUC(uc)}</span>`).join('');
  const lang = repo.language ? `<span class="badge lang-badge">${repo.language}</span>` : '';

  return `
    <a class="card${rankCls}" href="${repo.url}" target="_blank" rel="noopener">
      <div class="card-header">
        <span class="rank-badge">${rankLbl}</span>
        <div class="card-actions">
          <span class="star-box" style="color:var(--gold)">${STAR_SVG} ${fmtNum(repo.stars)}</span>
          <button class="fav-btn${isSaved ? ' saved' : ''}"
                  onclick="event.preventDefault();event.stopPropagation();toggleFav(${repo.id},this)"
                  title="${isSaved ? '❤' : '♡'}">
            ${isSaved ? '❤' : '♡'}
          </button>
        </div>
      </div>
      <div class="card-name"><span class="owner">${owner}/</span>${name}</div>
      <div class="card-desc">${repo.description || t('no_desc')}</div>
      <div class="card-footer">
        <div class="card-ucs">${ucTags}</div>
        <div class="card-meta">
          ${lang}
          <span class="badge cat-badge ${repo.category}">${catIcon} ${catLbl}</span>
          <span class="fork-info">🍴${fmtNum(repo.forks)} · ${timeAgo(repo.updated_at)}</span>
        </div>
      </div>
    </a>`;
}

/* ── List view ──────────────────────────────────────────────────── */
function renderList() {
  const grid = document.getElementById('grid');
  if (grid) grid.style.display = 'none';
  const table = document.getElementById('listTable');
  if (!table) return;
  table.style.display = 'table';

  const start  = (app.currentPage - 1) * app.pageSize;
  const page   = app.filtered.slice(start, start + app.pageSize);
  const rankMap = new Map(app.allRepos.map((r, i) => [r.id, i + 1]));
  const cats   = app.data.categories;

  if (!page.length) {
    table.innerHTML = `<tbody><tr><td colspan="8">
      <div class="empty-state"><span class="icon">🔍</span><strong>${t('no_results')}</strong></div>
    </td></tr></tbody>`;
    return;
  }

  const thead = `<thead class="lt-head"><tr>
    <th>${t('col_rank')}</th>
    <th>${t('col_repo')}</th>
    <th>${t('col_stars')}</th>
    <th>${t('col_uses')}</th>
    <th>${t('col_cat')}</th>
    <th>${t('col_lang')}</th>
    <th>${t('col_updated')}</th>
    <th></th>
  </tr></thead>`;

  const tbody = '<tbody>' + page.map(repo => {
    const gr = rankMap.get(repo.id) ?? 999;
    const emoji = gr === 1 ? '🥇' : gr === 2 ? '🥈' : gr === 3 ? '🥉' : `#${gr}`;
    const rkCls = gr <= 3 ? ` lt-rank-${gr}` : '';
    const [owner, name] = repo.full_name.split('/');
    const isSaved = app.favorites.has(repo.id);
    const catLbl = tCat(cats[repo.category]?.label || repo.category);
    const catIcon = cats[repo.category]?.icon || '';
    const ucTags = (repo.use_cases || []).slice(0, 3).map(uc =>
      `<span class="uc-tag${app.selectedUCs.has(uc) ? ' active' : ''}"
             onclick="toggleUC('${uc}')">${tUC(uc)}</span>`).join(' ');

    return `<tr class="lt-row">
      <td class="lt-rank${rkCls}">${emoji}</td>
      <td class="lt-name">
        <a href="${repo.url}" target="_blank" rel="noopener">
          <span class="owner">${owner}/</span>${name}
        </a>
        <div class="desc">${(repo.description || t('no_desc')).slice(0, 90)}</div>
      </td>
      <td class="lt-stars">★ ${fmtNum(repo.stars)}</td>
      <td class="lt-ucs">${ucTags}</td>
      <td class="lt-cat"><span class="badge cat-badge ${repo.category}">${catIcon} ${catLbl}</span></td>
      <td class="lt-lang">${repo.language || '—'}</td>
      <td class="lt-updated">${timeAgo(repo.updated_at)}</td>
      <td class="lt-fav">
        <button class="fav-btn${isSaved ? ' saved' : ''}"
                onclick="toggleFav(${repo.id},this)">
          ${isSaved ? '❤' : '♡'}
        </button>
      </td>
    </tr>`;
  }).join('') + '</tbody>';

  table.innerHTML = thead + tbody;
}

/* ── Pagination ─────────────────────────────────────────────────── */
function renderPagination() {
  const total = app.filtered.length;
  const pages = Math.ceil(total / app.pageSize);
  const pg    = document.getElementById('pagination');
  if (!pg) return;
  if (pages <= 1) { pg.innerHTML = ''; return; }

  const cur   = app.currentPage;
  const start = (cur - 1) * app.pageSize + 1;
  const end   = Math.min(cur * app.pageSize, total);
  const info  = `<span class="pg-info">${start}–${end} / ${total}</span>`;

  const nums = [];
  for (let i = 1; i <= pages; i++) {
    if (i === 1 || i === pages || (i >= cur - 2 && i <= cur + 2)) nums.push(i);
    else if (nums[nums.length - 1] !== '…') nums.push('…');
  }

  const pgBtns = nums.map(n =>
    n === '…'
      ? `<span class="pg-ellipsis">…</span>`
      : `<button class="pg-btn${n === cur ? ' active' : ''}" onclick="goPage(${n})">${n}</button>`
  ).join('');

  pg.innerHTML = `
    <button class="pg-btn" onclick="goPage(${cur - 1})" ${cur === 1 ? 'disabled' : ''}>←</button>
    ${pgBtns}
    <button class="pg-btn" onclick="goPage(${cur + 1})" ${cur === pages ? 'disabled' : ''}>→</button>
    ${info}`;
}

function goPage(n) {
  const pages = Math.ceil(app.filtered.length / app.pageSize);
  app.currentPage = Math.max(1, Math.min(n, pages));
  renderContent();
  renderPagination();
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

/* ── Render all (used on lang toggle) ──────────────────────────── */
function renderAll() {
  renderNav();
  renderHero();
  renderTabs();
  renderUCChips();
  renderLangSelect();
  applyFilters();
  applyThemeBtn();
  applyLangBtn();
}
