#!/usr/bin/env python3
"""Refresh the self-contained chrome/ extension and build its ZIP archive.

Python standard library only. Runtime files, icons, data, tests and this script
live in chrome/. The shareable ZIP is generated in chrome/dist/.
"""
import json
import re
from pathlib import Path
import shutil
import zipfile

CHROME = Path(__file__).resolve().parents[1]
ROOT = CHROME.parent
FIELDS = 'full_name description source_type category categories stars language topics platforms use_cases updated_at'.split()
BOARDS = {
    'skill': ('data', 'skills'), 'mcp': ('mcp_data', 'mcp'),
    'prompt': ('prompts_data', 'prompts'), 'framework': ('frameworks_data', 'frameworks'),
    'auto_research': ('auto_research_data', 'research'),
}


def build():
    payload = json.loads((ROOT / 'data/discovery_index.json').read_text())
    if not payload.get('items'):
        raise ValueError('The discovery index is empty. Run scripts/build_discovery_index.py first.')
    catalog = {'meta': payload['meta'], 'items': [{key: item.get(key, [] if key in ('topics', 'platforms', 'use_cases', 'categories') else '')
                                               for key in FIELDS} for item in payload['items']]}
    out = CHROME
    out.mkdir(parents=True, exist_ok=True)
    # Website data and navigation text are the source of truth, not a second hand-written taxonomy.
    site_js = (ROOT / 'src/shared.js').read_text(encoding='utf-8')
    taxonomy = {}
    for source, (filename, route) in BOARDS.items():
        board = json.loads((ROOT / f'data/{filename}.json').read_text(encoding='utf-8'))
        labels = re.findall(r'nav_' + route + r":\s*'([^']+)'", site_js)
        taxonomy[source] = {'label': labels[0], 'labelEn': labels[1], 'route': route,
                            'categories': {key: meta['label'] for key, meta in board['categories'].items()}}
    translations = {}
    for name in ['UC_EN', 'CAT_EN']:
        block = re.search(r'const ' + name + r' = \{(.*?)\n\};', site_js, re.S).group(1)
        translations[name] = dict(re.findall(r'"([^"]+)"\s*:\s*"([^"]+)"', block))
    (out / 'taxonomy.mjs').write_text('// Generated by scripts/build.py from website navigation and data.\n'
        + 'export const BOARDS = ' + json.dumps(taxonomy, ensure_ascii=False, indent=2) + ';\n'
        + ''.join('export const ' + name + ' = ' + json.dumps(values, ensure_ascii=False, indent=2) + ';\n'
                  for name, values in translations.items()), encoding='utf-8')
    files = []
    for source in sorted(out.iterdir()):
        if source.suffix in ('.json', '.html', '.css', '.js', '.mjs', '.md'):
            files.append(source.name)
    (out / 'data').mkdir(exist_ok=True)
    (out / 'data/catalog.json').write_text(json.dumps(catalog, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')
    files.append('data/catalog.json')
    # Icon assets are rendered from the checked-in SVG, never redrawn as opaque blocks.
    for name in ['logo.svg', 'icon-16.png', 'icon-32.png', 'icon-48.png', 'icon-128.png']:
        path = f'icons/{name}'
        if not (out / path).is_file():
            raise FileNotFoundError(f'Missing {path}; run chrome/scripts/render_icons.cjs first.')
        files.append(path)
    shutil.copy2(ROOT / 'LICENSE', out / 'LICENSE')
    files.append('LICENSE')
    archive = out / 'dist/agent-leaderboard-extension.zip'
    archive.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as handle:
        for name in sorted(files):
            handle.write(out / name, name)
    print(f'Built {len(catalog["items"]):,} catalog records → {out}')
    print(f'ZIP → {archive} ({archive.stat().st_size:,} bytes)')


if __name__ == '__main__':
    build()
